name: Run E2E tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker
      uses: docker/setup-qemu-action@v2

    - name: Build MongoDB for tests
      run: |
        docker-compose -f docker-compose.test.yml up -d --name e2e_mongo

    - name: Set up  replica set
      run: |
        docker-compose -f docker-compose.test.yml up -d --name e2e_mongosetup

    - name: Run tests
      run: |
        docker-compose -f docker-compose.test.yml up -d --name e2e_tests

    - name: Shutdown services
      run: |
        docker stop e2e_mongo e2e_mongosetup
        docker rm e2e_mongo e2e_mongosetup
        docker system prune -f --volumes