name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: sudo apt-get install docker-compose

    - name: Build and run Docker Compose services
      run: |
        docker-compose -f docker-compose.yml up -d
        until docker exec $(docker ps -q -f name=e2e_mongo) mongo --host localhost:27017 --eval 'rs.status()' | grep 'PRIMARY'; do
          echo 'Waiting for MongoDB replica set to initialize...';
          sleep 2;
        done

    - name: Run tests
      run: docker-compose run e2e_tests

    - name: Shutdown services
      run: docker-compose down --volumes
