name: Publish Docker Image When Pushing to Main

on:
  push:
    branches:
      - main

jobs:
  Publish Docker Image:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: sorrymybad3/monouser-platform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_REPO:${{ github.sha }} .
        docker tag $DOCKER_REPO:${{ github.sha }} $DOCKER_REPO:latest

    - name: Push Docker image with commit SHA
      run: docker push $DOCKER_REPO:${{ github.sha }}

    - name: Push Docker image with latest tag
      run: docker push $DOCKER_REPO:latest
